// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqpDxHVeTwMD1ufAPeY0V04nhRUEhd00g',
    appId: '1:842163687137:web:6229c9c0fd8e9f091fb1a0',
    messagingSenderId: '842163687137',
    projectId: 'note-app-35011',
    authDomain: 'note-app-35011.firebaseapp.com',
    storageBucket: 'note-app-35011.firebasestorage.app',
    measurementId: 'G-4HCBEWW7EW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCwt5bW7NfCuNsesFXVt_vbsfg8x8XNmbk',
    appId: '1:842163687137:android:14e14fd03fad48f81fb1a0',
    messagingSenderId: '842163687137',
    projectId: 'note-app-35011',
    storageBucket: 'note-app-35011.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4AdQqSdXGalswyuhn38FCagMOZh5x6iI',
    appId: '1:842163687137:ios:5d3a22e31a30f2c71fb1a0',
    messagingSenderId: '842163687137',
    projectId: 'note-app-35011',
    storageBucket: 'note-app-35011.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4AdQqSdXGalswyuhn38FCagMOZh5x6iI',
    appId: '1:842163687137:ios:5d3a22e31a30f2c71fb1a0',
    messagingSenderId: '842163687137',
    projectId: 'note-app-35011',
    storageBucket: 'note-app-35011.firebasestorage.app',
    iosBundleId: 'com.example.noteApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqpDxHVeTwMD1ufAPeY0V04nhRUEhd00g',
    appId: '1:842163687137:web:cdbb38bf96911f931fb1a0',
    messagingSenderId: '842163687137',
    projectId: 'note-app-35011',
    authDomain: 'note-app-35011.firebaseapp.com',
    storageBucket: 'note-app-35011.firebasestorage.app',
    measurementId: 'G-T0RKTTZDR7',
  );
}
